![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [3]:
my_array = np.arange(0,10)
print(my_array[1::2][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
print(my_array[-3:-1][::-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
print(my_array[:3][::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [6]:
matrix = np.arange(1,21).reshape(4,5)
matrix[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [7]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
matrix[:2, :2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [9]:
matrix[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:
matrix[:3:, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [11]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [12]:
np.where(x=="Loro", "Loro","")

array(['Loro', '', '', 'Loro', ''], dtype='<U4')

In [13]:
for palabra in x:
    if palabra =="Loro":
        print(palabra)

Loro
Loro


In [14]:
filtro=([True, False, False, True, False])
x[filtro]


array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [15]:
secuencia = np.arange(0,20).reshape(2,5,2)
secuencia

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [16]:
matrix[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [17]:
ceros = np.full(10, 0)
ceros.nbytes
ceros[3]=1
ceros


array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [18]:
vector = np.arange(10,50)
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [19]:
vect=np.array([1,2,0,0,4,0])
np.argwhere(vect != 0)

array([[0],
       [1],
       [4]])

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [20]:
matrix1 = np.random.rand(10,10)
print(matrix1)
print(matrix1.min())
print(matrix1.max())

[[0.52088046 0.25045119 0.28367971 0.96965015 0.37114926 0.09376096
  0.77162697 0.16533658 0.54700264 0.08680249]
 [0.25419863 0.08121371 0.62848512 0.57832481 0.07172321 0.87501214
  0.34798689 0.54618552 0.06267091 0.02073757]
 [0.23595825 0.3278572  0.50479684 0.05339642 0.59474658 0.69431579
  0.62825613 0.18116946 0.40560666 0.86726059]
 [0.36417826 0.96320142 0.34949905 0.45434597 0.92559447 0.42998745
  0.13029597 0.77812009 0.13474946 0.85942512]
 [0.21554865 0.4046024  0.74713391 0.94990425 0.37300193 0.63009271
  0.06345505 0.06444783 0.45111979 0.37342593]
 [0.46827465 0.42954954 0.41687827 0.92011944 0.30720486 0.11652547
  0.69847954 0.8357601  0.97928303 0.86304557]
 [0.05887673 0.97393037 0.14763578 0.15110156 0.87980581 0.4906617
  0.48809444 0.82392478 0.86933691 0.15633734]
 [0.62486489 0.88095135 0.76933372 0.14187443 0.2347246  0.5117271
  0.56665496 0.85532749 0.2975574  0.09423518]
 [0.88343461 0.02711314 0.33522904 0.97321862 0.84208815 0.72002425
  0.28964011 0

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [21]:
vect2 = np.random.rand(30)
print(vect2)
vect2.mean()

[0.10596848 0.27088464 0.13680929 0.20846079 0.52987518 0.40260229
 0.1428589  0.43122815 0.8975957  0.00637537 0.2717017  0.9371361
 0.88300191 0.34742831 0.74892037 0.4537146  0.71978239 0.2540872
 0.2542544  0.35607827 0.46568478 0.87077606 0.9518699  0.50040549
 0.94335703 0.91569639 0.96931692 0.15726043 0.90222782 0.6674916 ]


np.float64(0.5234283489121181)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [22]:
cuadrado = np.full((6,6), 0)
cuadrado[:1]=1
cuadrado[-1:]=1
cuadrado[::, :1:]=1
cuadrado[::, -1::]=1
cuadrado

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [23]:
cuadrado1 = np.full((6,6), 1)
cuadrado1[1:-1, 1:-1]=0
cuadrado1

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [24]:
cuadrado2 = np.full((8, 8), 1)
cuadrado2[::2, ::2]=0
cuadrado2[1::2, 1::2]=0
cuadrado2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [25]:
a = np.array([0, 1])
b = np.array([1, 0])
c = np.tile(a, (2)), np.tile(b, (2))
np.tile(c, (4,2))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [26]:
matrix4 = np.random.rand(5,5)
media = np.mean(matrix4)
desv = np.std(matrix4)
normalizada = (matrix4 - media)/desv

In [27]:
normalizada

array([[-0.53800594, -0.41683382, -1.02834959,  1.53243662, -1.05956758],
       [ 1.60724615,  0.95426736, -1.4728879 ,  1.0562736 , -0.44203866],
       [ 0.50597396, -0.65225313,  0.6223779 , -0.24648503, -1.14304851],
       [-0.81711614,  1.54917921, -1.00833894,  0.84451072, -1.55707074],
       [ 1.62874539, -0.35073968,  0.12179211,  0.67314509, -0.36321246]])

In [28]:
matriz4 = np.random.rand(5,5)

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [33]:
sec1 = np.arange(10)
sec2 = np.where((sec1>3) & (sec1<8), -1, sec1)
sec3 = np.where((sec1>3) & (sec1<8), not (-1), sec1)
print(sec2)
print(sec3)

[ 0  1  2  3 -1 -1 -1 -1  8  9]
[0 1 2 3 0 0 0 0 8 9]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [3]:
tablero = np.full((10,10),"")

In [4]:
tablero

array([['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [6]:
TABLERO_SIZE= (10,10)
tablero = np.full(TABLERO_SIZE, " ")

# eslora = np.random.randint(1, 5)

barquitos = [4,3,2,1]

for eslora in barquitos:

    orientacion = np.random.choice(["H", "V"])

    if orientacion == "H":
        horizontal = np.random.randint(0,10-(eslora-1))
        vertical = np.random.randint(0, 10)
    if orientacion == "V":
        vertical = np.random.randint(0,10-(eslora-1))
        horizontal = np.random.randint(0, 10)


    coordenada = [vertical, horizontal]
    if orientacion == "H":
        tablero[coordenada[0], coordenada[1]:coordenada[1]+eslora] = "o"
    else:
        tablero[coordenada[0]:coordenada[0]+eslora, coordenada[1]] = "o"
tablero

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'o', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', 'o', 'o', 'o', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', 'o', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', 'o', 'o', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', 'o', 'o', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', 'o', ' ', ' ']], dtype='<U1')